### ISSUE TITLE
Add tests to GitHub workflow for depended gems

### ISSUE THREAD

**Issue by mico** [relaton/relaton-index#10]
Test that relaton-* gems tests are still passsing, similar to what we did for `pubid-core`
@ronaldtse @andrew2net anything to add?

**Comment by andrew2net** [comment]
@CAMOBAP can you help here? But I see that in pubid-core depended gems are tested after pubid-core is released. Can we change the order to testing before releasing? We should't release a gem if any of its dependency crashes.

**Comment by CAMOBAP** [comment]
@andrew2net yep I will help

Just to be on the same page before the release of `relaton-index` we need to run `rake` for all `relaton-*` with  `relaton-index` from GitHub, right?

P.S. @mico does it make sense to do pre-release testing for `pubid-core` too?

**Comment by andrew2net** [comment]
> Just to be on the same page before the release of `relaton-index` we need to run `rake` for all `relaton-*` with `relaton-index` from GitHub, right?

@CAMOBAP Yes, we need to run rake for `relaton-*` with `relaton-index` GitHub version before release `relaton-index`, but not for all `relaton-*`, only listed in JSON file like in `pubid-core`. For nowadays the list is:
```
relaton-3gpp
relaton-bipm
relaton-calconnect
relaton-ccsds
relaton-cie
relaton-ecma
relaton-etsi
relaton-iana
relaton-iec
relaton-ieee
relaton-ietf
relaton-iho
relaton-iso
relaton-itu
relaton-nist
relaton-oasis
relaton-ogc
relaton-plateau
relaton-w3c
relaton-xsf
```

**Comment by mico** [comment]
@CAMOBAP tests for all gems fails now:
```
Run bundle exec rake

An error occurred while loading spec_helper. - Did you mean?
                    rspec ./spec/spec_helper.rb

Failure/Error: require "relaton/index"

LoadError:
  cannot load such file -- relaton/index
# ./lib/relaton_3gpp.rb:4:in `require'
# ./lib/relaton_3gpp.rb:4:in `<top (required)>'
# ./spec/spec_helper.rb:14:in `require'
# ./spec/spec_helper.rb:14:in `<top (required)>'
No examples found.
No examples found.
```

the step where you replacing `relaton-index` with latest one have dependency resolution errors:
```
Because every version of relaton-index depends on relaton-logger ~> 0.1.0
  and relaton-bib >= 1.19.0 depends on relaton-logger ~> 0.2.0,
  every version of relaton-index is incompatible with relaton-bib >= 1.19.0.
And because every version of relaton-bipm depends on relaton-bib ~> 1.19.0,
  every version of relaton-index is incompatible with relaton-bipm >= 0.
So, because Gemfile depends on relaton-bipm >= 0
  and Gemfile depends on relaton-index >= 0,
  version solving has failed.
```

**Comment by CAMOBAP** [comment]
@mico hmm yesterday I didn't observe such issue https://github.com/relaton/relaton-index/actions/runs/10203797435/job/28230898021

To be on the same page how I can help with it?
To me it's a clear transitive dependency version conflict and highly likely `relaton-logger` version should be increased to 0.2.0, did I missed something?

**Comment by mico** [comment]
> @mico hmm yesterday I didn't observe such issue https://github.com/relaton/relaton-index/actions/runs/10203797435/job/28230898021
> 
> To be on the same page how I can help with it? To me it's a clear transitive dependency version conflict and highly likely `relaton-logger` version should be increased to 0.2.0, did I missed something?

@CAMOBAP at your link everything looks good, no dependency conflicts, but here are https://github.com/relaton/relaton-index/actions/runs/10210644958
what changed?

**Comment by andrew2net** [comment]
> @mico hmm yesterday I didn't observe such issue https://github.com/relaton/relaton-index/actions/runs/10203797435/job/28230898021
> 
> To be on the same page how I can help with it? To me it's a clear transitive dependency version conflict and highly likely `relaton-logger` version should be increased to 0.2.0, did I missed something?

@CAMOBAP you are right, the `relaton-logger` version should be 0.2.0. This is why we need to do all these tests before release. Thank you for your contribution.

**Comment by mico** [comment]
@CAMOBAP dependencies error fixed, so now workflow works well. Thank you 🙏
