### ISSUE TITLE
cehck_basic_format misspelled + Issue in IETF-TOOLS relaton-data-ids

### ISSUE THREAD

**Issue by stefanomunarini** [relaton/relaton-index#3]
[`cehck_basic_format`](https://github.com/relaton/relaton-index/blame/126953d9688b0ede95d80607852f1cc600788e3a/lib/relaton/index/file_io.rb#L82) should perhaps be `check_basic_format`.

Moreover, [ietf-tool/relaton-data-ids](https://github.com/ietf-tools/relaton-data-ids/actions/runs/5878577476/job/15940932622) has been failing since Sunday. 

Can you help with this @andrew2net ?

**Comment by andrew2net** [comment]
@stefanomunarini fixed in v0.2.6
As I know index files are not used in the `ietf-tool/relaton-data-*` repos. You can remove the `index-v1.*` files and don't commit them anymore.

**Comment by stefano-tech-ai** [comment]
Thank you @andrew2net
